server:
  http2:
    enabled: true
  compression:
    enabled: true
    min-response-size: 1B

management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    ROOT: trace
